.TH miniirc_idc 1 miniirc_idc\-0.0.1
.SH NAME
miniirc_idc \- miniirc framework module for Internet Delay Chat
.SH DESCRIPTION
.B miniirc_idc
is a random sus thing made by luk3yx
.SH CONTACT
.LP
Write to idc (at) andrewyu (dot) org.
.SH AUTHORS
luk3yx <https://luk3yx.github.io>
.SH SEE ALSO
.BR miniirc (1)
.SH BUGS
There are many.  Please report.
